export {
  addStudentCompetence,
  addStudentExperience,
  addStudentFormation,
  addStudentLangue,
  createStudentProfile,
  deleteStudentExperience,
  getCvDownloadUrl,
  getMyStudentProfile,
  getStudentWorkspace,
  listStudentCompetences,
  listStudentExperiences,
  listStudentFormations,
  listStudentLangues,
  updateMyStudentProfile,
  uploadStudentCv,
} from '../features/student/services/student.service'
