version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: talentbridge-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: talentbridge-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@talentbridge.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres

  auth-service:
    build: ./services/auth-service
    container_name: auth-service
    ports:
      - "5001:5001"
    env_file:
      - ./services/auth-service/.env
    volumes:
      - ./services/auth-service:/app
      - /app/node_modules
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  pgdata: