version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: talentbridge-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: talentbridge_db
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - talentbridge-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: talentbridge-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@talentbridge.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8888:80"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - talentbridge-net

  auth-service:
    build: ./services/auth-service
    container_name: auth-service
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/talentbridge_db
      - JWT_SECRET=your_jwt_secret_key_change_this
    volumes:
      - ./services/auth-service:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - talentbridge-net
    restart: unless-stopped

  candidature-service:
    build: ./services/candidature-service
    container_name: candidature-service
    ports:
      - "5002:5002"
    environment:
      - PORT=5002
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=talentbridge_db
      - JWT_SECRET=your_jwt_secret_key_change_this
    volumes:
      - ./services/candidature-service:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - talentbridge-net
    restart: unless-stopped

  ai-document-service:
    build: ./services/ai-document-service
    container_name: ai-document-service
    ports:
      - "5003:5003"
    environment:
      - PORT=5003
      - GEMINI_API_KEY=AIzaSyBeUzFeaCXoBn2GwkijGlo4LdTuBEPp6LM
      - JWT_SECRET=your_jwt_secret_key_change_this
    volumes:
      - ./services/ai-document-service:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - talentbridge-net
    restart: unless-stopped

  api-gateway:
    build: ./services/api-gateway
    container_name: api-gateway
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
    depends_on:
      - auth-service
      - candidature-service
      - ai-document-service
    networks:
      - talentbridge-net
    restart: unless-stopped

networks:
  talentbridge-net:
    driver: bridge

volumes:
  pgdata: